<Project>
  <PropertyGroup>
    <WarningsAsErrors>$(WarningsAsErrors);CS4014</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup Condition="'$(MSBuildProjectExtension)' == '.csproj'">
    <Compile Include="$(MSBuildThisFileDirectory)GlobalSuppressions.cs" Link="GlobalSuppressions.cs" />
  </ItemGroup>
</Project>